### ISSUE TITLE
!support rolls the same races over and over

### ISSUE THREAD

**Issue by tranzmatt** [engooyen/majel#12]
Majel seems to have a fixation on Denobulans, Betazoids and Bajorans.  They're the only races that seem to appear with the !support command.  I've run over 20 and they're all one of those 3.

**Comment by engooyen** [comment]
Hi @tranzmatt,

I only have 4 species implemented: Andorian, Bajoran, Betazoid, and Denobulan. I'll get the rest of them in today. I'll probably add an option to list what species are supported just in case I miss a few. It will make it easy to report which ones I'm missing and from which source book.

-John

**Comment by engooyen** [comment]
@tranzmatt The remaining species are up. If you want to see the available species, use !support list.

**Comment by kkotenko** [comment]
@engooyen What is our goal for the character generator in general? To have all the species from all the source books? I could invest time in implementing the species based on the info from [the official character generator](https://sta.modiphiusapps.hostinguk.org/), and had in fact started it, but quickly realized there are a lot of species I had never even heard about. So in practice, I would have to go "Arbazan? I have no idea what that is *re-rolls five times*"

On the other hand, I would love to have support for more species. To find a sensible trade-off, I have the following

**Proposal:**

- [ ] Extend the existing data structure by an attribute "Source" which contains info on what the source book for the species is
- [ ] Add a command parameter to generate a character from a particular sourcebook only (if you are playing in, say, the Delta quadrant, you probably would want characters from that source book only)
- [ ] Add a command parameter to generate a character of a particular species (I often want, like, a random Klingon)
- [ ] Extend the existing data structure by an attribute "Genders" which lists the available genders (for example, Species 8472 have five, while the Borg have none.  There are a lot of other examples in the [wiki](https://memory-alpha.fandom.com/wiki/Gender#Other_variants_of_sex_and_gender). I am also open to having "Pronouns" here instead (I believe Borg drones are usually referred to as "it"?).
- [ ] Add a command parameter to generate characters of a particular gender 

If that's all okay with you, I would implement that at some point™.

I guess I am emotionally invested in this because those randomizers are my favourite feature of Majel. For me, generating a random part of the world is the hardest part, and it can be fun to think of how to add the character to the world. 

> You walk into the bar on the promenade. The barkeeper is... uh *rolls* a Tactical Borg drone.

**Comment by engooyen** [comment]
@kkotenko I don't we'll need to implement something as comprehensive as the character generator. The original vision I had for Majel is for her to be the embodiment of the sourcebooks, but in an accessible way. Speaking specifically about species, I would like the ones in the sourcebooks to be represented here. Your proposal so far looks great. The data entry portion of this project is rather boring. I'll think about a tool or something to streamline the data entry. Could you create a new ticket for each of your bullet points so that we can track and divvy the work if needed?

**Comment by kkotenko** [comment]
@engooyen I opened #21... #32. I think that's all.
